In [24]:
# Import 
import pandas as pd
import numpy as np

import os

#  load the pickle file
path = '/Users/am/Desktop/CF Data Analysis essentials /2_Data Analytics Immersions_2 von 3/4 Phyton/4.7/Prepared Data'
file_path = os.path.join(path, 'ords_prods_merge_updated.pkl')

# Load the dataframe
df = pd.read_pickle(file_path)

# Check the shape and a preview
print(df.shape)
df.head()

print(df.columns.tolist())

(32404859, 15)
['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow', 'order_hour_of_day', 'days_since_prior_order', 'product_id', 'add_to_cart_order', 'reordered', '_merge', 'product_name', 'aisle_id', 'department_id', 'prices']

In [25]:
df.groupby('product_name')

In [26]:
df['mean_product_price'] = df.groupby(['user_id'])['prices'].transform('mean')
df.loc[df['mean_product_price']<10,'spending_flag']='Low_spender'
df.loc[df['mean_product_price']>= 10, 'spending_flag']='High_spender'

df['spending_flag'].value_counts(dropna = False)

spending_flag
Low_spender     31770614
High_spender      634245
Name: count, dtype: int64

In [27]:
# Aggregating the mean order_number per department
df.groupby('department_id').agg({'order_number': ['mean']})

              order_number
                      mean
department_id
1                15.457838
2                17.277920
3                17.170395
4                17.811403
5                15.215751
6                16.439806
7                17.225802
8                15.340650
9                15.895474
10               20.197148
11               16.170638
12               15.887671
13               16.583536
14               16.773669
15               16.165037
16               17.665606
17               15.694469
18               19.310397
19               17.177343
20               16.473447
21               22.902379

In [29]:
df.groupby('department_id')['order_number'].mean()

department_id
1     15.457838
2     17.277920
3     17.170395
4     17.811403
5     15.215751
6     16.439806
7     17.225802
8     15.340650
9     15.895474
10    20.197148
11    16.170638
12    15.887671
13    16.583536
14    16.773669
15    16.165037
16    17.665606
17    15.694469
18    19.310397
19    17.177343
20    16.473447
21    22.902379
Name: order_number, dtype: float64

In [6]:
df.groupby('department_id').agg({'order_number': ['mean', 'min', 'max']})

              order_number
                      mean min max
department_id
1                15.457838   1  99
2                17.277920   1  99
3                17.170395   1  99
4                17.811403   1  99
5                15.215751   1  99
6                16.439806   1  99
7                17.225802   1  99
8                15.340650   1  99
9                15.895474   1  99
10               20.197148   1  99
11               16.170638   1  99
12               15.887671   1  99
13               16.583536   1  99
14               16.773669   1  99
15               16.165037   1  99
16               17.665606   1  99
17               15.694469   1  99
18               19.310397   1  99
19               17.177343   1  99
20               16.473447   1  99
21               22.902379   1  99

In [30]:
df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

df.head(17)

/var/folders/bx/glkbqc4x44qdk4_cp2ssyhl00000gn/T/ipykernel_20368/3612334811.py:1: FutureWarning: The provided callable <function max at 0x106a7bd80> is currently using SeriesGroupBy.max. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "max" instead.
  df['max_order'] = df.groupby(['user_id'])['order_number'].transform(np.max)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,mean_product_price,spending_flag,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,6.367797,Low_spender,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
2,473747,1,prior,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
4,431534,1,prior,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
6,550135,1,prior,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,3.980556,Low_spender,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
14,487368,15,prior,22,1,10,14.0,196,1,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
15,2293453,19,prior,2,5,14,6.0,196,3,0,both,Soda,77,7,9.0,8.372059,Low_spender,9
16,1973799,19,prior,5,6,12,8.0,196,15,1,both,Soda,77,7,9.0,8.372059,Low_spender,9

In [31]:
df.head(100)

,order_id,user_id,eval_set,order_number,order_dow,order_hour_of_day,days_since_prior_order,product_id,add_to_cart_order,reordered,_merge,product_name,aisle_id,department_id,prices,mean_product_price,spending_flag,max_order
0,2539329,1,prior,1,2,8,NaN,196,1,0,both,Soda,77,7,9.0,6.367797,Low_spender,10
1,2398795,1,prior,2,3,7,15.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
2,473747,1,prior,3,3,12,21.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
3,2254736,1,prior,4,4,7,29.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
4,431534,1,prior,5,4,15,28.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
5,3367565,1,prior,6,2,7,19.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
6,550135,1,prior,7,1,9,20.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
7,3108588,1,prior,8,1,14,14.0,196,2,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
8,2295261,1,prior,9,1,16,0.0,196,4,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
9,2550362,1,prior,10,4,8,30.0,196,1,1,both,Soda,77,7,9.0,6.367797,Low_spender,10
10,2968173,15,prior,15,1,9,7.0,196,2,0,both,Soda,77,7,9.0,3.980556,Low_spender,22
11,1870022,15,prior,17,2,16,8.0,196,6,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
12,1911383,15,prior,18,2,11,7.0,196,1,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
13,2715276,15,prior,21,1,9,7.0,196,1,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
14,487368,15,prior,22,1,10,14.0,196,1,1,both,Soda,77,7,9.0,3.980556,Low_spender,22
15,2293453,19,prior,2,5,14,6.0,196,3,0,both,Soda,77,7,9.0,8.372059,Low_spender,9
16,1973799,19,prior,5,6,12,8.0,196,15,1,both,Soda,77,7,9.0,8.372059,Low_spender,9
17,532817,19,prior,7,4,17,6.0,196,1,1,both,Soda,77,7,9.0,8.372059,Low_spender,9
18,1573906,21,prior,10,3,10,6.0,196,2,0,both,Soda,77,7,9.0,7.012683,Low_spender,33
19,1593000,31,prior,10,3,8,7.0,196,17,0,both,Soda,77,7,9.0,8.137793,Low_spender,20
20,2231262,31,prior,17,3,11,8.0,196,14,1,both,Soda,77,7,9.0,8.137793,Low_spender,20
21,2580647,43,prior,6,4,16,4.0,196,9,0,both,Soda,77,7,9.0,7.444898,Low_spender,11
22,2187180,43,prior,9,4,12,3.0,196,1,1,both,Soda,77,7,9.0,7.444898,Low_spender,11
23,2497897,52,prior,1,1,9,NaN,196,4,0,both,Soda,77,7,9.0,6.356287,Low_spender,27
24,1318871,52,prior,2,1,10,7.0,196,5,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
25,1261384,52,prior,3,1,10,7.0,196,3,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
26,580568,52,prior,5,2,10,8.0,196,6,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
27,2428073,52,prior,7,2,7,8.0,196,5,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
28,342306,52,prior,9,1,11,7.0,196,5,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
29,1520353,52,prior,10,2,10,8.0,196,4,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
30,2542086,52,prior,11,2,9,7.0,196,3,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
31,944694,52,prior,12,1,16,6.0,196,7,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
32,1268191,52,prior,15,2,11,8.0,196,3,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
33,1122089,52,prior,17,2,10,6.0,196,4,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
34,1498922,52,prior,18,2,10,14.0,196,6,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
35,180919,52,prior,19,3,8,8.0,196,4,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
36,2695875,52,prior,21,5,10,30.0,196,1,1,both,Soda,77,7,9.0,6.356287,Low_spender,27
37,3205960,67,prior,1,3,11,NaN,196,1,0,both,Soda,77,7,9.0,7.656790,Low_spender,24
38,970922,67,prior,2,1,15,5.0,196,2,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
39,596585,67,prior,3,1,13,7.0,196,2,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
40,2037087,67,prior,4,2,9,8.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
41,2474111,67,prior,5,3,14,8.0,196,2,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
42,1568481,67,prior,6,3,12,7.0,196,2,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
43,2048527,67,prior,8,2,11,7.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
44,2389031,67,prior,9,2,14,7.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
45,2378562,67,prior,10,1,10,6.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
46,1515698,67,prior,11,1,11,7.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
47,1928050,67,prior,12,2,12,8.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
48,1949274,67,prior,13,1,10,6.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
49,551869,67,prior,14,1,9,7.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
50,768572,67,prior,16,4,10,9.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
51,150528,67,prior,18,5,16,4.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
52,29758,67,prior,19,0,14,9.0,196,2,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
53,1558976,67,prior,21,1,9,5.0,196,2,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
54,863974,67,prior,22,1,11,14.0,196,3,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
55,2308399,67,prior,23,1,14,14.0,196,1,1,both,Soda,77,7,9.0,7.656790,Low_spender,24
56,2759128,81,prior,3,1,9,14.0,196,2,0,both,Soda,77,7,9.0,8.165385,Low_spender,7
57,1812985,81,prior,5,2,20,30.0,196,1,1,both,Soda,77,7,9.0,8.165385,Low_spender,7
58,1889835,82,prior,1,3,15,NaN,196,6,0,both,Soda,77,7,9.0,6.441221,Low_spender,19
59,499460,82,prior,3,5,10,5.0,196,2,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
60,2728456,82,prior,4,0,11,16.0,196,1,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
61,2653743,82,prior,6,4,9,13.0,196,5,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
62,1358880,82,prior,9,1,10,30.0,196,1,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
63,343588,82,prior,10,2,11,1.0,196,1,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
64,3034663,82,prior,15,2,11,12.0,196,1,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
65,147262,82,prior,18,1,13,7.0,196,1,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
66,3144004,82,prior,19,2,15,8.0,196,1,1,both,Soda,77,7,9.0,6.441221,Low_spender,19
67,2126069,98,prior,3,0,9,25.0,196,7,0,both,Soda,77,7,9.0,8.028000,Low_spender,14
68,2210120,98,prior,7,5,14,5.0,196,1,1,both,Soda,77,7,9.0,8.028000,Low_spender,14
69,681011,98,prior,9,3,9,30.0,196,1,1,both,Soda,77,7,9.0,8.028000,Low_spender,14
70,2846344,98,prior,11,4,13,15.0,196,2,1,both,Soda,77,7,9.0,8.028000,Low_spender,14
71,747431,98,prior,12,6,13,30.0,196,4,1,both,Soda,77,7,9.0,8.028000,Low_spender,14
72,2383054,98,prior,13,4,11,30.0,196,1,1,both,Soda,77,7,9.0,8.028000,Low_spender,14
73,1993729,98,prior,14,5,8,8.0,196,2,1,both,Soda,77,7,9.0,8.028000,Low_spender,14
74,1403849,109,prior,3,3,17,9.0,196,5,0,both,Soda,77,7,9.0,5.850725,Low_spender,6
75,520620,120,prior,1,3,11,NaN,196,2,0,both,Soda,77,7,9.0,9.385714,Low_spender,3
76,3273029,120,prior,3,2,8,19.0,196,2,1,both,Soda,77,7,9.0,9.385714,Low_spender,3
77,1861943,185,prior,2,1,12,25.0,196,10,0,both,Soda,77,7,9.0,7.715000,Low_spender,6
78,2040988,195,prior,1,1,14,NaN,196,2,0,both,Soda,77,7,9.0,7.149730,Low_spender,58
79,1680569,195,prior,8,1,9,4.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
80,276171,195,prior,19,5,11,3.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
81,2744976,195,prior,22,5,10,7.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
82,2781919,195,prior,25,1,14,4.0,196,1,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
83,1738718,195,prior,31,2,8,4.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
84,3058369,195,prior,34,3,10,6.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
85,1485596,195,prior,37,2,15,0.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
86,417035,195,prior,40,3,16,2.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
87,1615297,195,prior,47,5,10,2.0,196,2,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
88,1765587,195,prior,52,3,12,2.0,196,3,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
89,745908,195,prior,57,4,11,3.0,196,3,1,both,Soda,77,7,9.0,7.149730,Low_spender,58
90,2505656,222,prior,17,2,12,1.0,196,2,0,both,Soda,77,7,9.0,6.862397,Low_spender,70
91,3268370,222,prior,38,5,15,1.0,196,6,1,both,Soda,77,7,9.0,6.862397,Low_spender,70
92,2016711,290,prior,9,5,19,6.0,196,8,0,both,Soda,77,7,9.0,7.285597,Low_spender,51
93,2706088,290,prior,28,6,10,7.0,196,16,1,both,Soda,77,7,9.0,7.285597,Low_spender,51
94,1952286,331,prior,6,5,16,30.0,196,8,0,both,Soda,77,7,9.0,7.705128,Low_spender,8
95,3226575,360,prior,1,5,12,NaN,196,1,0,both,Soda,77,7,9.0,10.006250,High_spender,3
96,1469869,377,prior,3,5,17,3.0,196,9,0,both,Soda,77,7,9.0,8.496552,Low_spender,3
97,1927023,387,prior,2,4,10,22.0,196,3,0,both,Soda,77,7,9.0,7.396610,Low_spender,8
98,858092,420,prior,4,1,19,30.0,196,2,0,both,Soda,77,7,9.0,7.387805,Low_spender,22
99,119314,420,prior,5,3,19,16.0,196,2,1,both,Soda,77,7,9.0,7.387805,Low_spender,22

In [32]:
pd.options.display.max_rows = None

In [36]:
# Create the loyalty_flag column based on max_order
df.loc[df['max_order'] > 40, 'loyalty_flag'] = 'Loyal customer'
df.loc[(df['max_order'] <= 40) & (df['max_order'] > 10), 'loyalty_flag'] = 'Regular customer'
df.loc[df['max_order'] <= 10, 'loyalty_flag'] = 'New customer'

In [37]:
# Check value counts for the new loyalty_flag column
print(df['loyalty_flag'].value_counts())
print(df.columns)

loyalty_flag
Regular customer    15876776
Loyal customer      10284093
New customer         6243990
Name: count, dtype: int64
Index(['order_id', 'user_id', 'eval_set', 'order_number', 'order_dow',
       'order_hour_of_day', 'days_since_prior_order', 'product_id',
       'add_to_cart_order', 'reordered', '_merge', 'product_name', 'aisle_id',
       'department_id', 'prices', 'mean_product_price', 'spending_flag',
       'max_order', 'order_frequency_flag', 'loyalty_flag'],
      dtype='object')

In [34]:
# Calculate median days_since_prior_order per user
median_days = df.groupby('user_id')['days_since_prior_order'].transform('median')

# Create the frequency flag based on median_days
df.loc[median_days > 20, 'order_frequency_flag'] = 'Non-frequent customer'
df.loc[(median_days > 10) & (median_days <= 20), 'order_frequency_flag'] = 'Regular customer'
df.loc[median_days <= 10, 'order_frequency_flag'] = 'Frequent customer'

# Check value counts for the new loyalty_flag column
print(df['order_frequency_flag'].value_counts())

order_frequency_flag
Frequent customer        21559853
Regular customer          7208564
Non-frequent customer     3636437
nan                             5
Name: count, dtype: int64

In [38]:
path = '/Users/am/Desktop/CF Data Analysis essentials /2_Data Analytics Immersions_2 von 3/4 Phyton/4.8'
file_path = os.path.join(path, 'ords_prods_merge_final_4.8new.pkl')

df.to_pickle(file_path)

In [39]:
# Print confirmation
print(f"DataFrame successfully saved to: {file_path}")

DataFrame successfully saved to: /Users/am/Desktop/CF Data Analysis essentials /2_Data Analytics Immersions_2 von 3/4 Phyton/4.8/ords_prods_merge_final_4.8new.pkl